"""CLI: python -m backend --email-id email_001 [--json]."""

import argparse
import json
import sys
from pathlib import Path

from .ingestion import IngestionError, load_email
from .comparison import compare_email


def main() -> int:
    parser = argparse.ArgumentParser(description="Read, classify and verify shipping emails.")
    parser.add_argument("--email-id", default="email_001")
    parser.add_argument(
        "--dataset", type=Path,
        default=Path(__file__).resolve().parents[1] / "sdoc-hackathon-bundle",
        help="Directory containing inbox/ and attachments/",
    )
    parser.add_argument("--json", action="store_true", help="Print structured JSON output")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--compare", action="store_true", help="Manually request SI/BL comparison")
    mode.add_argument("--process", action="store_true", help="Run AI classification and route comparison requests")
    parser.add_argument("--model", type=Path, help="Local classifier artifact generated by model.train")
    args = parser.parse_args()
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    try:
        if args.process:
            from model.classifier import DEFAULT_MODEL, EmailClassifier
            from .pipeline import process_email
            result = process_email(args.dataset, args.email_id, EmailClassifier(args.model or DEFAULT_MODEL))
        else:
            result = load_email(args.dataset, args.email_id)
    except (IngestionError, ValueError, OSError, ImportError) as exc:
        if args.json:
            print(json.dumps({"error": str(exc)}, ensure_ascii=False))
        else:
            print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.compare or args.process:
        if args.compare:
            result = compare_email(result)
        if args.json:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        else:
            print(f"Email: {result['email_id']}\nComparison: {result['comparison_status']}")
            if args.process:
                prediction = result["classification"]
                print(f"AI prediction: {prediction['predicted_category']} ({prediction['confidence']:.1%}, uncalibrated)")
                print(f"Routing: {result['routing_status']}")
                if result["routing_status"] == "CLASSIFIED_ONLY":
                    print("Classified only; document comparison is not required.")
            else:
                print("Manual comparison requested; AI classification has not run.")
            for field, values in result["fields"].items():
                print(f"\n{field}: {values['state']}")
                for side in ("si", "bl"):
                    item = values[side]
                    print(f"  {side.upper()}: {item['normalized_value'] if item else None}")
                    if item and item["source"]:
                        source = item["source"]
                        print(f"    {source['attachment_path']} lines {source['locator']['line_start']}-{source['locator']['line_end']}: {source['quote']}")
            if result["comparison_status"] == "OK":
                print("\nNo mismatch detected.")
            for detail in result["review_details"]:
                print(f"REVIEW: {detail}")
        needs_review = result["comparison_status"] == "NEEDS_REVIEW" or result.get("routing_status") == "CLASSIFICATION_REVIEW"
        return 2 if needs_review else 0

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        email = result["email"]
        print(f"Email: {email['email_id']}\nFrom: {email['from']}\nSubject: {email['subject']}")
        print(f"\n{email['body']}\n\nIngestion: {result['ingestion_status']}")
        if not result["documents"]:
            print("No attachments listed. Document requirements have not been checked.")
        for document in result["documents"]:
            print(f"\n--- {document['path']} [{document['status']}] ---")
            print(document["text"] if document["text"] is not None else document["error"])
        print("\nReading only: AI classification and SI/BL verification have not run.")
    return 2 if result["ingestion_status"] == "PARTIAL" else 0


if __name__ == "__main__":
    raise SystemExit(main())
